#pragma once
#include <winerror.h> //don't pay for what you don't use. 
namespace Skele_lib {
	namespace WinAPI {
	Schemadeletionfailed:attributeisusedincan -
			const char* GETErrorDiscription(size_t erno) {
			switch (erno) {
			case ERROR_SUCCESS: return "The operation completed successfully.";
			case ERROR_INVALID_FUNCTION: return "Incorrect function.";
			case ERROR_FILE_NOT_FOUND: return "The system cannot find the file specified.";
			case ERROR_PATH_NOT_FOUND: return "The system cannot find the path specified.";
			case ERROR_TOO_MANY_OPEN_FILES: return "The system cannot open the file.";
			case ERROR_ACCESS_DENIED: return "Access is denied.";
			case ERROR_INVALID_HANDLE: return "The handle is invalid.";
			case ERROR_ARENA_TRASHED: return "The storage control blocks were destroyed.";
			case ERROR_NOT_ENOUGH_MEMORY: return "Not enough storage is available to process this command.";
			case ERROR_INVALID_BLOCK: return "The storage control block address is invalid.";
			case ERROR_BAD_ENVIRONMENT: return "The environment is incorrect.";
			case ERROR_BAD_FORMAT: return "An attempt was made to load a program with an incorrect format.";
			case ERROR_INVALID_ACCESS: return "The access code is invalid.";
			case ERROR_INVALID_DATA: return "The data is invalid.";
			case ERROR_OUTOFMEMORY: return "Not enough storage is available to complete this operation.";
			case ERROR_INVALID_DRIVE: return "The system cannot find the drive specified.";
			case ERROR_CURRENT_DIRECTORY: return "The directory cannot be removed.";
			case ERROR_NOT_SAME_DEVICE: return "The system cannot move the file to a different disk drive.";
			case ERROR_NO_MORE_FILES: return "There are no more files.";
			case ERROR_WRITE_PROTECT: return "The media is write protected.";
			case ERROR_BAD_UNIT: return "The system cannot find the device specified.";
			case ERROR_NOT_READY: return "The device is not ready.";
			case ERROR_BAD_COMMAND: return "The device does not recognize the command.";
			case ERROR_CRC: return "Data error (cyclic redundancy check).";
			case ERROR_BAD_LENGTH: return "The program issued a command but the command length is incorrect.";
			case ERROR_SEEK: return "The drive cannot locate a specific area or track on the disk.";
			case ERROR_NOT_DOS_DISK: return "The specified disk or diskette cannot be accessed.";
			case ERROR_SECTOR_NOT_FOUND: return "The drive cannot find the sector requested.";
			case ERROR_OUT_OF_PAPER: return "The printer is out of paper.";
			case ERROR_WRITE_FAULT: return "The system cannot write to the specified device.";
			case ERROR_READ_FAULT: return "The system cannot read from the specified device.";
			case ERROR_GEN_FAILURE: return "A device attached to the system is not functioning.";
			case ERROR_SHARING_VIOLATION: return "The process cannot access the file because it is being used by another process.";
			case ERROR_LOCK_VIOLATION: return "The process cannot access the file because another process has locked a portion of the file.";
			case ERROR_WRONG_DISK: return "The wrong diskette is in the drive. Insert %2 (Volume Serial Number: %3) into drive %1.";
			case ERROR_SHARING_BUFFER_EXCEEDED: return "Too many files opened for sharing.";
			case ERROR_HANDLE_EOF: return "Reached the end of the file.";
			case ERROR_HANDLE_DISK_FULL: return "The disk is full.";
			case ERROR_NOT_SUPPORTED: return "The network request is not supported.";
			case ERROR_REM_NOT_LIST: return "The remote computer is not available.";
			case ERROR_DUP_NAME: return "A duplicate name exists on the network.";
			case ERROR_BAD_NETPATH: return "The network path was not found.";
			case ERROR_NETWORK_BUSY: return "The network is busy.";
			case ERROR_DEV_NOT_EXIST: return "The specified network resource or device is no longer available.";
			case ERROR_TOO_MANY_CMDS: return "The network BIOS command limit has been reached.";
			case ERROR_ADAP_HDW_ERR: return "A network adapter hardware error occurred.";
			case ERROR_BAD_NET_RESP: return "The specified server cannot perform the requested operation.";
			case ERROR_UNEXP_NET_ERR: return "An unexpected network error occurred.";
			case ERROR_BAD_REM_ADAP: return "The remote adapter is not compatible.";
			case ERROR_PRINTQ_FULL: return "The printer queue is full.";
			case ERROR_NO_SPOOL_SPACE: return "Space to store the file waiting to be printed is not available on the server.";
			case ERROR_PRINT_CANCELED: return "Your file waiting to be printed was deleted.";
			case ERROR_NETNAME_DELETED: return "The specified network name is no longer available.";
			case ERROR_NETWORK_ACCESS_DENIED: return "Network access is denied.";
			case ERROR_BAD_DEV_TYPE: return "The network resource type is not correct.";
			case ERROR_BAD_NET_NAME: return "The network name cannot be found.";
			case ERROR_TOO_MANY_NAMES: return "The name limit for the local computer network adapter card was exceeded.";
			case ERROR_TOO_MANY_SESS: return "The network BIOS session limit was exceeded.";
			case ERROR_SHARING_PAUSED: return "The remote server has been paused or is in the process of being started.";
			case ERROR_REQ_NOT_ACCEP: return "No more connections can be made to this remote computer at this time because there are already as many connections as the computer can accept.";
			case ERROR_REDIR_PAUSED: return "The specified printer or disk device has been paused.";
			case ERROR_FILE_EXISTS: return "The file exists.";
			case ERROR_CANNOT_MAKE: return "The directory or file cannot be created.";
			case ERROR_FAIL_I24: return "Fail on INT 24.";
			case ERROR_OUT_OF_STRUCTURES: return "Storage to process this request is not available.";
			case ERROR_ALREADY_ASSIGNED: return "The local device name is already in use.";
			case ERROR_INVALID_PASSWORD: return "The specified network password is not correct.";
			case ERROR_INVALID_PARAMETER: return "The parameter is incorrect.";
			case ERROR_NET_WRITE_FAULT: return "A write fault occurred on the network.";
			case ERROR_NO_PROC_SLOTS: return "The system cannot start another process at this time.";
			case ERROR_TOO_MANY_SEMAPHORES: return "Cannot create another system semaphore.";
			case ERROR_EXCL_SEM_ALREADY_OWNED: return "The exclusive semaphore is owned by another process.";
			case ERROR_SEM_IS_SET: return "The semaphore is set and cannot be closed.";
			case ERROR_TOO_MANY_SEM_REQUESTS: return "The semaphore cannot be set again.";
			case ERROR_INVALID_AT_INTERRUPT_TIME: return "Cannot request exclusive semaphores at interrupt time.";
			case ERROR_SEM_OWNER_DIED: return "The previous ownership of this semaphore has ended.";
			case ERROR_SEM_USER_LIMIT: return "Insert the diskette for drive %1.";
			case ERROR_DISK_CHANGE: return "The program stopped because an alternate diskette was not inserted.";
			case ERROR_DRIVE_LOCKED: return "The disk is in use or locked by another process.";
			case ERROR_BROKEN_PIPE: return "The pipe has been ended.";
			case ERROR_OPEN_FAILED: return "The system cannot open the device or file specified.";
			case ERROR_BUFFER_OVERFLOW: return "The file name is too long.";
			case ERROR_DISK_FULL: return "There is not enough space on the disk.";
			case ERROR_NO_MORE_SEARCH_HANDLES: return "No more internal file identifiers available.";
			case ERROR_INVALID_TARGET_HANDLE: return "The target internal file identifier is incorrect.";
			case ERROR_INVALID_CATEGORY: return "The IOCTL call made by the application program is not correct.";
			case ERROR_INVALID_VERIFY_SWITCH: return "The verify-on-write switch parameter value is not correct.";
			case ERROR_BAD_DRIVER_LEVEL: return "The system does not support the command requested.";
			case ERROR_CALL_NOT_IMPLEMENTED: return "This function is not supported on this system.";
			case ERROR_SEM_TIMEOUT: return "The semaphore timeout period has expired.";
			case ERROR_INSUFFICIENT_BUFFER: return "The data area passed to a system call is too small.";
			case ERROR_INVALID_NAME: return "The filename, directory name, or volume label syntax is incorrect.";
			case ERROR_INVALID_LEVEL: return "The system call level is not correct.";
			case ERROR_NO_VOLUME_LABEL: return "The disk has no volume label.";
			case ERROR_MOD_NOT_FOUND: return "The specified module could not be found.";
			case ERROR_PROC_NOT_FOUND: return "The specified procedure could not be found.";
			case ERROR_WAIT_NO_CHILDREN: return "There are no child processes to wait for.";
			case ERROR_CHILD_NOT_COMPLETE: return "The %1 application cannot be run in Win32 mode.";
			case ERROR_DIRECT_ACCESS_HANDLE: return "Attempt to use a file handle to an open disk partition for an operation other than raw disk I/O.";
			case ERROR_NEGATIVE_SEEK: return "An attempt was made to move the file pointer before the beginning of the file.";
			case ERROR_SEEK_ON_DEVICE: return "The file pointer cannot be set on the specified device or file.";
			case ERROR_IS_JOIN_TARGET: return "A JOIN or SUBST command cannot be used for a drive that contains previously joined drives.";
			case ERROR_IS_JOINED: return "An attempt was made to use a JOIN or SUBST command on a drive that has already been joined.";
			case ERROR_IS_SUBSTED: return "An attempt was made to use a JOIN or SUBST command on a drive that has already been substituted.";
			case ERROR_NOT_JOINED: return "The system tried to delete the JOIN of a drive that is not joined.";
			case ERROR_NOT_SUBSTED: return "The system tried to delete the substitution of a drive that is not substituted.";
			case ERROR_JOIN_TO_JOIN: return "The system tried to join a drive to a directory on a joined drive.";
			case ERROR_SUBST_TO_SUBST: return "The system tried to substitute a drive to a directory on a substituted drive.";
			case ERROR_JOIN_TO_SUBST: return "The system tried to join a drive to a directory on a substituted drive.";
			case ERROR_SUBST_TO_JOIN: return "The system tried to SUBST a drive to a directory on a joined drive.";
			case ERROR_BUSY_DRIVE: return "The system cannot perform a JOIN or SUBST at this time.";
			case ERROR_SAME_DRIVE: return "The system cannot join or substitute a drive to or for a directory on the same drive.";
			case ERROR_DIR_NOT_ROOT: return "The directory is not a subdirectory of the root directory.";
			case ERROR_DIR_NOT_EMPTY: return "The directory is not empty.";
			case ERROR_IS_SUBST_PATH: return "The path specified is being used in a substitute.";
			case ERROR_IS_JOIN_PATH: return "Not enough resources are available to process this command.";
			case ERROR_PATH_BUSY: return "The path specified cannot be used at this time.";
			case ERROR_IS_SUBST_TARGET: return "An attempt was made to join or substitute a drive for which a directory on the drive is the target of a previous substitute.";
			case ERROR_SYSTEM_TRACE: return "System trace information was not specified in your CONFIG.SYS file, or tracing is disallowed.";
			case ERROR_INVALID_EVENT_COUNT: return "The number of specified semaphore events for DosMuxSemWait is not correct.";
			case ERROR_TOO_MANY_MUXWAITERS: return "DosMuxSemWait did not execute; too many semaphores are already set.";
			case ERROR_INVALID_LIST_FORMAT: return "The DosMuxSemWait list is not correct.";
			case ERROR_LABEL_TOO_LONG: return "The volume label you entered exceeds the label character limit of the target file system.";
			case ERROR_TOO_MANY_TCBS: return "Cannot create another thread.";
			case ERROR_SIGNAL_REFUSED: return "The recipient process has refused the signal.";
			case ERROR_DISCARDED: return "The segment is already discarded and cannot be locked.";
			case ERROR_NOT_LOCKED: return "The segment is already unlocked.";
			case ERROR_BAD_THREADID_ADDR: return "The address for the thread ID is not correct.";
			case ERROR_BAD_ARGUMENTS: return "The argument string passed to DosExecPgm is not correct.";
			case ERROR_BAD_PATHNAME: return "The specified path is invalid.";
			case ERROR_SIGNAL_PENDING: return "A signal is already pending.";
			case ERROR_MAX_THRDS_REACHED: return "No more threads can be created in the system.";
			case ERROR_LOCK_FAILED: return "Unable to lock a region of a file.";
			case ERROR_BUSY: return "The requested resource is in use.";
			case ERROR_CANCEL_VIOLATION: return "A lock request was not outstanding for the supplied cancel region.";
			case ERROR_ATOMIC_LOCKS_NOT_SUPPORTED: return "The file system does not support atomic changes to the lock type.";
			case ERROR_INVALID_SEGMENT_NUMBER: return "The system detected a segment number that was not correct.";
			case ERROR_INVALID_ORDINAL: return "The operating system cannot run %1.";
			case ERROR_ALREADY_EXISTS: return "Cannot create a file when that file already exists.";
			case ERROR_INVALID_FLAG_NUMBER: return "The flag passed is not correct.";
			case ERROR_SEM_NOT_FOUND: return "The specified system semaphore name was not found.";
			case ERROR_INVALID_STARTING_CODESEG: return "The operating system cannot run %1.";
			case ERROR_INVALID_STACKSEG: return "The operating system cannot run %1.";
			case ERROR_INVALID_MODULETYPE: return "The operating system cannot run %1.";
			case ERROR_INVALID_EXE_SIGNATURE: return "Cannot run %1 in Win32 mode.";
			case ERROR_EXE_MARKED_INVALID: return "The operating system cannot run %1.";
			case ERROR_BAD_EXE_FORMAT: return "%1 is not a valid Win32 application.";
			case ERROR_ITERATED_DATA_EXCEEDS_64k: return "The operating system cannot run %1.";
			case ERROR_INVALID_MINALLOCSIZE: return "The operating system cannot run %1.";
			case ERROR_DYNLINK_FROM_INVALID_RING: return "The operating system cannot run this application program.";
			case ERROR_IOPL_NOT_ENABLED: return "The operating system is not presently configured to run this application.";
			case ERROR_INVALID_SEGDPL: return "The operating system cannot run %1.";
			case ERROR_AUTODATASEG_EXCEEDS_64k: return "The operating system cannot run this application program.";
			case ERROR_RING2SEG_MUST_BE_MOVABLE: return "The code segment cannot be greater than or equal to 64K.";
			case ERROR_RELOC_CHAIN_XEEDS_SEGLIM: return "The operating system cannot run %1.";
			case ERROR_INFLOOP_IN_RELOC_CHAIN: return "The operating system cannot run %1.";
			case ERROR_ENVVAR_NOT_FOUND: return "The system could not find the environment option that was entered.";
			case ERROR_NO_SIGNAL_SENT: return "No process in the command subtree has a signal handler.";
			case ERROR_FILENAME_EXCED_RANGE: return "The filename or extension is too long.";
			case ERROR_RING2_STACK_IN_USE: return "The ring 2 stack is in use.";
			case ERROR_META_EXPANSION_TOO_LONG: return "The global filename characters, * or ?, are entered incorrectly or too many global filename characters are specified.";
			case ERROR_INVALID_SIGNAL_NUMBER: return "The signal being posted is not correct.";
			case ERROR_THREAD_1_INACTIVE: return "The signal handler cannot be set.";
			case ERROR_LOCKED: return "The segment is locked and cannot be reallocated.";
			case ERROR_TOO_MANY_MODULES: return "Too many dynamic-link modules are attached to this program or dynamic-link module.";
			case ERROR_NESTING_NOT_ALLOWED: return "Cannot nest calls to LoadModule.";
			case ERROR_EXE_MACHINE_TYPE_MISMATCH: return "The image file %1 is valid, but is for a machine type other than the current machine.";
			case ERROR_BAD_PIPE: return "The pipe state is invalid.";
			case ERROR_PIPE_BUSY: return "All pipe instances are busy.";
			case ERROR_NO_DATA: return "The pipe is being closed.";
			case ERROR_PIPE_NOT_CONNECTED: return "No process is on the other end of the pipe.";
			case ERROR_MORE_DATA: return "More data is available.";
			case ERROR_VC_DISCONNECTED: return "The session was canceled.";
			case ERROR_INVALID_EA_NAME: return "The specified extended attribute name was invalid.";
			case ERROR_EA_LIST_INCONSISTENT: return "The extended attributes are inconsistent.";
			case WAIT_TIMEOUT: return "The wait operation timed out.";
			case ERROR_NO_MORE_ITEMS: return "No more data is available.";
			case ERROR_CANNOT_COPY: return "The copy functions cannot be used.";
			case ERROR_DIRECTORY: return "The directory name is invalid.";
			case ERROR_EAS_DIDNT_FIT: return "The extended attributes did not fit in the buffer.";
			case ERROR_EA_FILE_CORRUPT: return "The extended attribute file on the mounted file system is corrupt.";
			case ERROR_EA_TABLE_FULL: return "The extended attribute table file is full.";
			case ERROR_INVALID_EA_HANDLE: return "The specified extended attribute handle is invalid.";
			case ERROR_EAS_NOT_SUPPORTED: return "The mounted file system does not support extended attributes.";
			case ERROR_NOT_OWNER: return "Attempt to release mutex not owned by caller.";
			case ERROR_TOO_MANY_POSTS: return "Too many posts were made to a semaphore.";
			case ERROR_PARTIAL_COPY: return "Only part of a ReadProcessMemory or WriteProcessMemory request was completed.";
			case ERROR_OPLOCK_NOT_GRANTED: return "The oplock request is denied.";
			case ERROR_INVALID_OPLOCK_PROTOCOL: return "An invalid oplock acknowledgment was received by the system.";
			case ERROR_MR_MID_NOT_FOUND: return "The system cannot find message text for message number 0x%1 in the message file for %2.";
			case ERROR_INVALID_ADDRESS: return "Attempt to access invalid address.";
			case ERROR_ARITHMETIC_OVERFLOW: return "Arithmetic result exceeded 32 bits.";
			case ERROR_PIPE_CONNECTED: return "There is a process on other end of the pipe.";
			case ERROR_PIPE_LISTENING: return "Waiting for a process to open the other end of the pipe.";
			case ERROR_EA_ACCESS_DENIED: return "Access to the extended attribute was denied.";
			case ERROR_OPERATION_ABORTED: return "The I/O operation has been aborted because of either a thread exit or an application request.";
			case ERROR_IO_INCOMPLETE: return "Overlapped I/O event is not in a signaled state.";
			case ERROR_IO_PENDING: return "Overlapped I/O operation is in progress.";
			case ERROR_NOACCESS: return "Invalid access to memory location.";
			case ERROR_SWAPERROR : return "Error performing inpage operation.";
			default: return "invalid or unsuported error number";
			}
		}
	}
}